apiVersion: v1
kind: Pod
metadata:
  name: pix-api
spec:
  containers:
  - name: pix-api
    image: cbmdevacr.azurecr.io/play-express:latest
  imagePullSecrets:
  - name: cbmdevacr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: pix-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3003
    protocol: TCP
